[build]
  command = "python3 --version && npm run build"
  publish = ".next"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[build.lifecycle]
  onBuild = "pip install -r functions/predict/requirements.txt"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[functions."predict"]
  included_files = [
    "functions/predict/model.py",
    "functions/predict/model.pth"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"
