# Build settings
[build]
  command = "python3 --version && npm run build"
  publish = ".next"
  functions = "functions"

# Set Python version for the build environment
[build.environment]
  PYTHON_VERSION = "3.9"

# Install Python dependencies during build
[build.lifecycle]
  onBuild = """
    echo 'Installing Python dependencies' && 
    pip install -r functions/predict/requirements.txt && 
    echo 'Installation complete' && 
    ls -alh functions/predict/
  """

# Define function directory and bundler
[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Include specific files for the "predict" function
[functions."predict"]
  included_files = [
    "functions/predict/model.py",
    "functions/predict/predict.js",
    "functions/predict/model.pth",
    "functions/predict/handler.py"
  ]

# Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
