[build]
  command = "npm run build"
  publish = ".next"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.11"

[functions]
  node_bundler = "esbuild"

[functions.predict]
  external_node_modules = ["onnxruntime-node"]
  included_files = ["model.onnx"]


[[plugins]]
  package = "@netlify/plugin-nextjs"