[build]
  command = "pip install -r requirements.txt && npm run build"
  publish = ".next"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.11"

[functions]
  node_bundler = "esbuild"

[functions.predict]
  included_files = ["src/model/model.py", "src/model/model.pth" ]

[[plugins]]
  package = "@netlify/plugin-nextjs"